name: todo-list # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple todo list app # 79 char long summary
title: Todo List
description: |
  Todo-list built with Tauri + WebKitGTK 4.1 for Linux.
license: MIT
contact: vhgcuong95@gmail.com
source-code: https://github.com/vhgcuong/todo-list.git
issues: https://github.com/vhgcuong/todo-list.git/issues

grade: stable
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

apps:
  todo-list:
    command: usr/bin/todo-list
    desktop: usr/share/applications/todo-list.desktop
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libfontconfig1
      - fontconfig
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - xdg-utils
      - dpkg
      - nodejs
      - npm
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libwayland-client0
      - libxkbcommon0
      - libglib2.0-0
      - libgtk-3-0
      - libsoup2.4-1
    # source-type: git
    source: .
    override-build: |
      set -eu
      rustup default stable

      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install -g pnpm
      pnpm install
      pnpm run tauri build
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=todo-list|Icon=/usr/share/icons/hicolor/32x32/apps/todo-list.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/todo-list.desktop

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.addictiontracker

lint:
  ignore:
    - metadata:
        - website
        - donation